<?xml version="1.0" standalone="yes"?>
<!DOCTYPE CAABOM [
<!ELEMENT CAABOM (PRODUCT, ITEM+) >
<!ELEMENT PRODUCT (#PCDATA) >
<!ELEMENT ITEM (ATTRIBUTE+,QUANTITY) >
<!ELEMENT ATTRIBUTE ANY >
<!ATTLIST ATTRIBUTE name CDATA #REQUIRED>
<!ELEMENT QUANTITY (#PCDATA) >
]>
<?xml-stylesheet type="text/xsl" href="CAAPstBOM.xml"?>
<CAABOM>
<PRODUCT>CAAPstSkateboard0620---</PRODUCT> 
<ITEM>
<ATTRIBUTE name="PLM_ExternalID">CAAPstDeck05421</ATTRIBUTE> 
<ATTRIBUTE name="V_version">---</ATTRIBUTE> 
<ATTRIBUTE name="V_description">Santa Cruz Coffin model</ATTRIBUTE> 
<ATTRIBUTE name="C_created"> 14 June 2006 16:04:42.</ATTRIBUTE> 
<ATTRIBUTE name="C_modified"> 14 June 2006 16:04:53.</ATTRIBUTE> 
<ATTRIBUTE name="V_maturity">IN_WORK</ATTRIBUTE> 
<ATTRIBUTE name="LOCKUSER"></ATTRIBUTE> 
<ATTRIBUTE name="V_discipline"></ATTRIBUTE> 
<ATTRIBUTE name="V_usage"></ATTRIBUTE> 
<ATTRIBUTE name="V_project">DEFAULT</ATTRIBUTE> 
<ATTRIBUTE name="V_user">TNE</ATTRIBUTE> 
<ATTRIBUTE name="V_organization">VPM</ATTRIBUTE> 
<ATTRIBUTE name="V_IndustryCode">L0605</ATTRIBUTE> 
<ATTRIBUTE name="V_StdNumber"></ATTRIBUTE> 
<ATTRIBUTE name="V_BOM"></ATTRIBUTE> 
<ATTRIBUTE name="V_Supplier">true</ATTRIBUTE> 
<QUANTITY>1</QUANTITY>
</ITEM>
<ITEM>
<ATTRIBUTE name="PLM_ExternalID">CAAPstSmallWheel06019</ATTRIBUTE> 
<ATTRIBUTE name="V_version">---</ATTRIBUTE> 
<ATTRIBUTE name="V_description">Spitfire Smallhead model</ATTRIBUTE> 
<ATTRIBUTE name="C_created"> 14 June 2006 16:04:42.</ATTRIBUTE> 
<ATTRIBUTE name="C_modified"> 14 June 2006 16:04:53.</ATTRIBUTE> 
<ATTRIBUTE name="V_maturity">IN_WORK</ATTRIBUTE> 
<ATTRIBUTE name="LOCKUSER"></ATTRIBUTE> 
<ATTRIBUTE name="V_discipline"></ATTRIBUTE> 
<ATTRIBUTE name="V_usage"></ATTRIBUTE> 
<ATTRIBUTE name="V_project">DEFAULT</ATTRIBUTE> 
<ATTRIBUTE name="V_user">TNE</ATTRIBUTE> 
<ATTRIBUTE name="V_organization">VPM</ATTRIBUTE> 
<ATTRIBUTE name="V_IndustryCode">V0416</ATTRIBUTE> 
<ATTRIBUTE name="V_StdNumber"></ATTRIBUTE> 
<ATTRIBUTE name="V_BOM"></ATTRIBUTE> 
<ATTRIBUTE name="V_Supplier">true</ATTRIBUTE> 
<QUANTITY>4</QUANTITY>
</ITEM>
<ITEM>
<ATTRIBUTE name="PLM_ExternalID">CAAPstBigWheel06019</ATTRIBUTE> 
<ATTRIBUTE name="V_version">---</ATTRIBUTE> 
<ATTRIBUTE name="V_description">Spitfire Bighead model</ATTRIBUTE> 
<ATTRIBUTE name="C_created"> 14 June 2006 16:04:42.</ATTRIBUTE> 
<ATTRIBUTE name="C_modified"> 14 June 2006 17:36:49.</ATTRIBUTE> 
<ATTRIBUTE name="V_maturity">IN_WORK</ATTRIBUTE> 
<ATTRIBUTE name="LOCKUSER"></ATTRIBUTE> 
<ATTRIBUTE name="V_discipline"></ATTRIBUTE> 
<ATTRIBUTE name="V_usage"></ATTRIBUTE> 
<ATTRIBUTE name="V_project">DEFAULT</ATTRIBUTE> 
<ATTRIBUTE name="V_user">TNE</ATTRIBUTE> 
<ATTRIBUTE name="V_organization">VPM</ATTRIBUTE> 
<ATTRIBUTE name="V_IndustryCode">V0416</ATTRIBUTE> 
<ATTRIBUTE name="V_StdNumber"></ATTRIBUTE> 
<ATTRIBUTE name="V_BOM"></ATTRIBUTE> 
<ATTRIBUTE name="V_Supplier">true</ATTRIBUTE> 
<QUANTITY>4</QUANTITY>
</ITEM>
<ITEM>
<ATTRIBUTE name="PLM_ExternalID">CAAPstTruck06019</ATTRIBUTE> 
<ATTRIBUTE name="V_version">---</ATTRIBUTE> 
<ATTRIBUTE name="V_description">Independant Plan 9 model</ATTRIBUTE> 
<ATTRIBUTE name="C_created"> 14 June 2006 16:04:42.</ATTRIBUTE> 
<ATTRIBUTE name="C_modified"> 14 June 2006 17:36:49.</ATTRIBUTE> 
<ATTRIBUTE name="V_maturity">IN_WORK</ATTRIBUTE> 
<ATTRIBUTE name="LOCKUSER"></ATTRIBUTE> 
<ATTRIBUTE name="V_discipline"></ATTRIBUTE> 
<ATTRIBUTE name="V_usage"></ATTRIBUTE> 
<ATTRIBUTE name="V_project">DEFAULT</ATTRIBUTE> 
<ATTRIBUTE name="V_user">TNE</ATTRIBUTE> 
<ATTRIBUTE name="V_organization">VPM</ATTRIBUTE> 
<ATTRIBUTE name="V_IndustryCode">X3141</ATTRIBUTE> 
<ATTRIBUTE name="V_StdNumber"></ATTRIBUTE> 
<ATTRIBUTE name="V_BOM"></ATTRIBUTE> 
<ATTRIBUTE name="V_Supplier">true</ATTRIBUTE> 
<QUANTITY>2</QUANTITY>
</ITEM>
</CAABOM>
